# site information
site_name: "Cinéphile: top movies / films"
site_url: https://hantang.github.io/cinephile
site_author: hantang
site_description: "Top movie collections"
copyright: Copyright &copy; 2023-2024 Hantang
# docs_dir: docs/

# Repository
repo_name: hantang/cinephile
repo_url: https://github.com/hantang/cinephile
# edit_uri: tree/main

theme:
  name: material
  # language: "zh"
  icon:
    logo: material/movie
  font:
    text: Helvetica Neue, Roboto
    code: Fira Mono, Fira Code, Roboto Mono
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  features:
    - navigation.path
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    # - toc.integrate

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 4
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          percent_encode: true
  - mdx_truly_sane_lists
  - tables

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.number.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.date.js
  - assets/js/tablesort.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hantang

plugins:
  - search
  - table-reader
  - git-revision-date-localized
  - minify:
      minify_html: true

nav:
  - Home:
    - 电影万岁: index.md
  - FI&FF:
    - 专业榜单: fiff/index.md
    - 榜单资料1: fiff/index-media.md
    - 榜单资料2: fiff/index-region.md
    - 法国《电影手册》(Cahiers du cinéma): fiff/cahiers.md
    - 法国《电影手册》(Cahiers du cinéma)Top100: fiff/cahiers-100.md
    - 英国《视与听》(BFI, Sight & Sound): fiff/sight.md
    - 日本《电影旬报》: fiff/kinejun.md
    - 美国标准收藏公司（The Criterion Collection）: fiff/criterion.md
    - 美国电影协会AFI: fiff/afi.md
    - 韩国釜山电影节（BIFF）: fiff/biff.md
    - 迷影网: fiff/cinephilia.md
    - 国别（地区）榜单:
      - 中国电影: fiff/films-zh.md
      - 香港电影: fiff/films-hk.md
      - 日本电影: fiff/films-jp.md
  - Douban:
    - 豆瓣电影: douban/index.md
    - 豆瓣电影年度榜单汇总: douban/douban-annual.md
    - 豆瓣电影2023年Top250: douban/douban-2023.md
    - 豆瓣电影Top250历史归档: douban/douban-hist.md
  - IMDb:
    - IMDb电影: imdb/index.md
    - IMDb电影2023年Top250: imdb/imdb-2023.md
  - TSPDT:
    - TSPDT电影: tspdt/index.md
    - TSPDT电影2024年榜单: tspdt/tspdt-2024.md
    - TSPDT电影2023年榜单: tspdt/tspdt-2023.md
    - TSPDT电影历年统计(2006-2024): tspdt/tspdt-top1000-archive.md
    - TSPDT电影历年统计(2003-2005): tspdt/tspdt-top1000-archive-v1.md
    - TSPDT21世纪电影统计(2008-2024): tspdt/tspdt-top1000-21stcentury.md
  - More:
    - 大众榜单: 
      - popular/index.md
    - 个人片单: 
      - users/index.md
      - 1001电影系列: users/1001movies.md
      - 杂项: users/misc.md
    - 猫眼电影Top100: popular/maoyan.md
    - 时光电影Top100: popular/mtime.md
    - TMDB电影Top250: popular/tmdb.md
    - 俄罗斯Kinopoisk Top250: popular/kinopoisk.md
    - 不散评选: popular/busan.md
