# site information
site_name: "cinéphile: top movies / films"
site_url: https://hantang.github.io/cinephile
site_description: top movie collections
copyright: Copyright &copy; 2023 Hantang
# docs_dir: docs/

# Repository
repo_url: https://github.com/hantang/cinephile
# edit_uri: tree/main

theme:
  name: material
  # language: "zh"
  icon:
    logo: material/movie
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: Helvetica Neue, Roboto
    code: Fira Code, Roboto Mono
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.footer
    - navigation.sections
    - navigation.path
    - navigation.tracking
    - toc.follow
    - content.tabs.link
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotations

markdown_extensions:
  - footnotes
  - abbr
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hantang

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

plugins:
  - search
  - table-reader
  - minify:
      minify_html: true

nav:
  - Home:
      - Films: index.md
      - 豆瓣电影: douban/index.md
      - IMDb电影: imdb/index.md
      - TSPDT电影: tspdt/index.md
      - 电影协会和电影节: fiff/index.md
      - 补充: more/index.md
  - Douban豆瓣:
      - 豆瓣电影: douban/index.md
      - 豆瓣电影历史榜单: douban/douban-hist.md
      - 豆瓣电影2023榜单: douban/douban-2023.md
  - IMDb:
      - IMDb电影: imdb/index.md
      - IMDb电影2023年榜单: imdb/imdb-2023.md
  - TSPDT:
      - TSPDT电影: tspdt/index.md
      - TSPDT电影2023年榜单: tspdt/tspdt-2023.md
  - Film ORG:
      - 电影协会和电影节: fiff/index.md
      - BFI(Sight & Sound)视与听: fiff/bfi.md
      - AFI美国电影协会: fiff/afi.md
      - BIFF釜山电影节: fiff/biff.md
  - More:
      - 补充: more/index.md
      - Mtime时光网: more/mtime.md
      - MaoYan猫眼: more/maoyan.md
      - TMDb: more/tmdb.md
      - Kinopoisk: more/kinopoisk.md
  # - FAQ:
  # - About:
