name: Deploy MkDocs Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-mkdocs.txt ]; then pip install -r requirements-mkdocs.txt; fi
      - name: Deploy mkdocs
        run: mkdocs gh-deploy --force
